config_version: '1.0'
config_name: base
config_steps:
    - data:
        dataset_version: 854b08fa-ab8b-47f2-a126-29f0d9783899 # NAME OF DATASET VERSION
    - transform:
    - model:
    - sample:
        number_of_rows: ''
    - metrics: